name: flappy_ember
description: A simple flappy birds-like game
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: 1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flame_lint: ^0.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/parallax/
    - assets/images/boxes/
    - assets/images/
